### PR TITLE
feat: add bitrate option

### PR DESCRIPTION
**Pull request by oupala**

### CODE REVIEW

**Comment by oupala** [comment]
I'm working on this pull request. I have two questions:

- how can you get the value of a parameter? I know how to check if a parameter has the value *a* or *b*, but I don't know how to get the numeric or text value of a parameter...
- using `ffmpeg` how would you set the resolution of a video? Looking at the [documentation of ffmpeg](https://ffmpeg.org/ffmpeg.html#Video-Options), I can only see the `-s[:stream_specifier] size (input/output,per-stream)` option or the `scale` option.

**Comment by rprieto** [comment]
Hi @oupala, thanks for the PR! For the parameter value do you mean the options like `{ bitrate: 1200 }`? If so, you can simply use `args.push('-b:v', options.bitrate)`.

Very good question about the resolution. It might not be available. If that's the case, the bitrate is already a very good start!

**Comment by oupala** [comment]
Once answered by you, the answer to my question seemed obvious. Thanks for the tip anyway.

I updated my commit and the pull request according to your advice. It is only about bitrate now.

**Comment by oupala** [comment]
Just waiting for your merge...

**Comment by rprieto** [comment]
I'm sorry I had forgotten about it, thanks for reminding me!

I'm looking at the existing code some more and some things jumped out:
- the code for de-interlacing MTS already contains bitrate options, with `-qscale:v 4` (variable bitrate).
- the else branch (non MTS) has another option (`-vb 1200k`), which actually looks like an alias for `v:b` but doesn't seem to be documented.

Looking at the docs (https://trac.ffmpeg.org/wiki/Encode/MPEG-4), variable bitrate seems to be preferable to constant bitrate, but both are important options.

What about offering both options, maybe something like`bitrate` (constant bitrate, the one you added, integer value) and `quality` (similar to the existing photo option, as a value between 1 and 100, sets variable bitrate compression)?

If that sounds good I'm happy to merge your PR and add the small change on top. I'll clean up that code block so that the `if (MTS)` only deals with interlacing.

**Comment by oupala** [comment]
I see that you merged my merge request, thanks for that.

Are you planning to add the small change on top and to clean up that code block?

**Comment by rprieto** [comment]
Hi, yes I'm working on it right now. Hopefully will commit it all today or tomorrow (it was trickier than expected because `qvalue` isn't supported by the H265 encoder).

**Comment by rprieto** [comment]
Hi @oupala, thanks for your patience. I just released `v2.2.0`. I will integrate all the new options (`--format`, `--bitrate` and `--quality`) into thumbsup shortly.

**Pull request merged**
