### PR TITLE
Retry still image without skipping frames on failure

### PR DESCRIPTION
**Pull request by tribut**
Some videos can't be seeked, either because they are too short or because the format doesn't support it. In this case, just take the very first frame as still image.

See https://github.com/thumbsup/thumbsup/issues/76

### CODE REVIEW

**Comment by rprieto** [comment]
That's great, thanks for the fix!

Do you have an example of a problematic video to add a unit test similar to https://github.com/thumbsup/downsize/blob/master/test/still.js#L12 ?

**Comment by tribut** [comment]
Hey. Didn't find a video without lots of innocent faces in it, so I took an example of a single-frame video and replaced the "video" stream with another picture using ffmpeg. Behaves just like the original, test and data is now included in the commit.

One thing I noticed that the test would succeed once it had succeed one time, even when I reverted the code change. This is due to ffmpeg exiting with code 0, but not generating an image. That means gm will resize the image it generated during the last run (which will pass the test). Should we clean up the target file before running ffmpeg to prevent this?

**Comment by rprieto** [comment]
Thanks! Now that there's a fallback for short videos, what do you think about moving the default seek back to say `5sec`? I think I initially added the seek to avoid bad previews if the video fades from black. Happy to make the change after merging your PR! Another option would be to remove the seek altogether.

**Comment by tribut** [comment]
Was thinking of that, too. Yes, moving back to something larger than `0.1` makes sense.

**Pull request merged**
