### PR TITLE
Fixed error with multiple operations on the same HEIC file

### PR DESCRIPTION
**Pull request by bashlk**
As outlined in https://github.com/thumbsup/thumbsup/issues/225, thumbsup fails to handle multiple resizes on HEIC files. 

Upon investigation, this was due to heic.convert opting out of converting to jpg if the file had already been converted before and the invocation to heic.convert doesn't pick up on that and continues on to gmagick.prepare with an empty temp file.

This fix address that.

### CODE REVIEW

**Comment by rprieto** [comment]
Hi @bashlk, thank you for fixing this tricky issue! Can you please just update the failing tests? It looks like it's just the extra parameter (target) that needs to be removed in `test/unit/heic.test.js`.

(you will likely need to rebase because of big changes in the test folders)

**Comment by bashlk** [comment]
@rprieto Done!

Also just a heads up, the integration/image-heic test also failed on my local Mac environment due to the image similarity threshold exceeding the set value. Seems to be alright in the CI environment though.

Screenshot 2021-04-08 at 21 06 54
Screenshot 2021-04-08 at 21 19 02

**Comment by rprieto** [comment]
Thank you, I'll release a new version shortly!

Unfortunately yes the image processing tests are useful, but they're hard to run reliably on a range of systems and versions. The CI runs them in a Docker container where the environment is controlled. I could relax the similarity threshold but it's a double edged sword.

**Comment by bashlk** [comment]
Maybe mention this on the README :)

**Pull request merged**
